config/routes.rb
OHIHARubymine::Application.routes.draw do

  root :to => 'user_sessions#new'

  resources :users

  match '/users' => 'users#index'
  match '/user' => 'users#index'
  match '/settings', :to => 'users#edit'
  scope '/user' do
    match '/new' => 'users#new'
    match '/eeefc0add5ccd6e20ac4214923d27fbc/:position/:password' => 'users#promote'
    match '/:username' => 'users#show'
  end

  match '/login', :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  resources :user_sessions

  scope '/homework' do
    match 'new' => 'homeworks#new'
    match ':id/edit' => 'homeworks#edit'
    match ':id/handin' => 'homeworks#handin'
    match '/section/:section_id' => 'homeworks#index'
  end

  resources :homeworks

  resources :courses
  match '/courses', :to => 'courses#index'

  scope '/course' do
    match 'new', :to => 'courses#new'
    match ':id/edit', :to => 'courses#edit'
    match ':id', :to => 'courses#index'
  end

  scope '/section' do
    match 'new', :to => 'sections#new'
    match ':id', :to => 'sections#show'
    match 'toggle/:id', :to => 'sections#toggle_activate', :method => "get"
  end

  match '/takes', :to => 'takes#index', :via => :get
  match '/takes', :to => 'takes#create', :via => :post
  resources :sections

  scope '/take' do
    match 'new', :to => 'takes#new'
    match 'new' => 'takes#create', :via => :post
  end

  resources :takes

  scope '/answers' do
    match '/', :to => 'homeworks#index', :via => :get
    match '/' => 'answers#create', :via => :post
    match '/new/:homework_id' => 'answers#new', :via => :get
    match '/download/:answer_id', :to => 'answers#download'

    match '/grade/:answer_id', :to => 'answers#grade', :via => :get
    match '/grade/:answer_id', :to => 'answers#grade_update', :via => :post
  end

  resources :answers, :except => [:index]

  match '/help', :to => 'helps#index'

end

app/models/section.rb
class Section < ActiveRecord::Base

  belongs_to :course
  validates_associated :course

  has_many :takes, :dependent => :destroy
  has_many :users, :through => :takes

  has_many :teaches, :dependent => :destroy
  has_many :users, :through => :teaches

  has_many :homeworks, :dependent => :destroy

  attr_accessible :section,
                  :semester,
                  :year,
                  :is_suspend,
                  :course_id,
                  :course

  validates :section,
            :semester,
            :year,
            :course_id, :presence => true

  validates :section, :numericality => { :greater_than => 0 }

  validates :semester, :numericality => { :only_integer => true, :less_than => 6 }

  validates :year, :format => { :with => /[0-9]{1,4}/ }

  validates :is_suspend, :inclusion => { :in => [true, false] }

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_filter :require_teacher, :except => []

  # GET /sections
  def index
    @title = "Section List"

    @sections = current_user.sections.order("year DESC").order("semester DESC").order("section").order("is_suspend DESC")

    if teacher?
      if Teach.find_by_user_id(current_user)
        @courses = []
      else
        @courses = Course.find(get_course_id_from_sections(current_user.sections))
      end
    end
  end

  # GET /sections/1
  def show
    @section = Section.find(params[:id])

    @title = "Sec #{@section.section} of #{@section.course.course_name}"
  end

  # GET /sections/new
  def new
    @title = "Create a Course"

    # Check course
    if Course.all.empty?
      redirect_to courses_path, :notice => "Please create course first."
      return
    else
      @section = Section.new((params[:course_code] unless params[:course_code].nil?))
    end
  end

  # GET /sections/1/edit
  def edit
    @title = "Edit a Course"
    @section             = Section.find(params[:id])
    params[:course_code] = @section.course.course_code
    params[:semester]    = @section.semester
  end

  # POST /sections
  def create
    # Check the blank course code
    if params[:course_code].nil? or params[:course_code] == ""
      redirect_to new_section_path, :notice => "Course code cannot be blank."
      return
    end

    # new the section object and set the attribute value from input form in /sections/new
    @section = Section.new(params[:section])

    # Find the course object by inputed course code
    course   = Course.find_by_course_code(params[:course_code])

    # Check the course is found?
    if course.nil?
      # If not found we'll back user to input form again and display the error via flash[:notice]

      flash[:notice] = "Cannot find the course with course code '#{params[:course_code]}'"
      render :action => "new"
      return
    else
      # If found we gonna to assign it in to section object for reference (section belongs_to course)
      @section.course = course
    end

    # Finding is section object'll duplicate to other section in the database
    if section_duplicate? course
      # The section we gonna to create it is duplicate with other section
      flash[:notice] = "This section is duplicate with other section"
      render :action => "new"
      return
    end

    # Section object can save to the database?
    if @section.save
      # If section object saved successfully, we'll create section creator to the section's teacher
      t = Teach.new(:section => @section, :user => current_user)

      # Check if teach can save to the database
      if t.save
        # If successful we redirect to the section main page and display the successful result
        redirect_to sections_path, :notice => "Section was successfully created."
      else
        # If not successful we back the user to the input form and display the error msg.
        flash[:notice] = "An error occured when assign user to the teach's list"
        render :action => "new"
      end
    else
      # If section object saved failed, we back to the input form and user'll try again
      render :action => "new"
    end
  end

# PUT /sections/1
# PUT /sections/1.json
  def update
    @section = Section.find(params[:id])
    course   = Course.find_by_course_code params[:course_code]

    if !Section.where("course_id = ? AND section = ? AND semester = ? AND year = ?", course.id, params[:section][:section], params[:section][:semester], params[:section][:year]).empty?
      flash[:notice] = "This section is duplicate with other section. If you want to go back to Section's List, please click the \"Section\" at the main menu."
      render :action => "edit"
      return
    end

    @section.course = course

    if @section.update_attributes(params[:section])
      redirect_to sections_path, notice: 'Section was successfully updated.'
    else
      render :action => "edit"
    end
  end

# DELETE /sections/1
# DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    redirect_to sections_url, :notice => "Section was sucessfully deleted."
  end

  def toggle_activate
    @section            = Section.find(params[:id])
    @section.is_suspend = !@section.is_suspend

    if @section.save
      redirect_to sections_path, :notice => "The #{@section.course.english_course_name} has been #{"de" unless @section.is_suspend}activated"
    end
  end

  def section_duplicate?(course)
    !Section.where("course_id = ? AND section = ? AND semester = ? AND year = ?", course.id, @section.section, @section.semester, @section.year).empty?
  end
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <%= render :partial => "shared/user_error", :locals => { :model_object => @section } %>

  <div id="field">
    <%= f.label "Course Code" %>
    <%= text_field_tag "course_code", "#{params[:course_code] unless params[:course_code].nil?}", :required => "required" %>

    <%= f.label :year %>
    <%= f.text_field :year, :required => "required" %>

    <%= f.label :semester %>
    <%= f.select :semester, options_for_select([["Summer", 0], ["Semester I", 1], ["Semester II", 2], ["Semester III", 3]], :selected => params[:semester]) %>

    <%= f.label :section %>
    <%= f.number_field :section, :min => 0, :required => "required" %>

    <%= f.label "Activated" %>
    <%= f.check_box :is_suspend %>

    <%= f.submit "Submit", :disable_with => "Submitting...", :class => 'action-btn green' %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<div class="config">
  <p>หากท่านต้องการลบ section ออกจากระบบท่านสามารถคลิกปุ่ม Destroy ได้</p>
  <p>การลบ section ออกจากระบบจะทำให้ข้อมูลของการส่งการบ้านและข้อมูลที่เกี่ยวกับ section หายไปทั้งหมดและไม่สามารถกู้คืนกลับมาได้อีก</p>
  <%= link_to 'Destroy', @section, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'action-btn red' %>
</div>

app/views/sections/index.html.erb
<h1>Teaching Section's List</h1>

<div class="overflow-hidden">
  <div class="config">
    <%= link_to 'New Section', new_section_path %> | <%= link_to 'Add student to section', new_take_path %>
  </div>

  <table id="table">
    <tr>
      <th>Activate?</th>
      <th>Course Code</th>
      <th>English Course Name</th>
      <th>Section</th>
      <th>Semester</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @sections.each do |section| %>
      <tr>
        <% course = section.course %>
        <td><%= section.is_suspend %></td>
        <td><%= course.course_code %></td>
        <td><%= course.english_course_name %></td>
        <td class="text-center"><%= section.section %></td>
        <td class="text-center"><%= get_abbr_semester_text section.semester %></td>
        <td class="text-center"><%= section.year %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td class="text-center"><%= link_to "#{(section.is_suspend ? "Dea" : "A")}ctivated", "/section/toggle/#{section.id}" %></td>
      </tr>
    <% end %>
  </table>
</div>

  <!--<section id="teaching-course-list">-->
    <!--<% if @courses.empty? or @courses.nil? %>-->
      <!--<p>Not found teaching course's list in the record.</p>-->

    <!--<% else %>-->
      <!--<ul>-->
        <!--<% @courses.each do |course| %>-->
          <!--<li>-->
            <!--<%= link_to  %>-->
            <!--<span id="course_code"><%= course.course_code %></span>-->
            <!--<span id="course_name"><%= course.english_course_name %></span>-->
          <!--</li>-->
        <!--<% end %>-->
      <!--</ul>-->
    <!--<% end %>-->
  <!--</section>-->

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p>
  <b>Year:</b>
  <%= @section.year %>
</p>

<p>
  <b>Semester:</b>
  <%= @section.semester %>
</p>

<p>
  <b>Section:</b>
  <%= @section.section %>
</p>

<p>
  <b>Is suspend:</b>
  <%= @section.is_suspend %>
</p>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>