config/routes.rb
OHIHARubymine::Application.routes.draw do

  root :to => 'user_sessions#new'

  resources :users

  match '/users' => 'users#index'
  match '/user' => 'users#index'
  match '/settings', :to => 'users#edit'
  scope '/user' do
    match '/new' => 'users#new'
    match '/eeefc0add5ccd6e20ac4214923d27fbc/:position/:password' => 'users#promote'
    match '/:username' => 'users#show'
  end

  match '/login', :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  resources :user_sessions

  scope '/homework' do
    match 'new' => 'homeworks#new'
    match ':id/edit' => 'homeworks#edit'
    match ':id/handin' => 'homeworks#handin'
    match '/section/:section_id' => 'homeworks#index'
  end

  resources :homeworks

  resources :courses
  match '/courses', :to => 'courses#index'

  scope '/course' do
    match 'new', :to => 'courses#new'
    match ':id/edit', :to => 'courses#edit'
    match ':id', :to => 'courses#index'
  end

  scope '/section' do
    match 'new', :to => 'sections#new'
    match ':id', :to => 'sections#show'
    match 'toggle/:id', :to => 'sections#toggle_activate', :method => "get"
  end

  match '/takes', :to => 'takes#index', :via => :get
  match '/takes', :to => 'takes#create', :via => :post
  resources :sections

  scope '/take' do
    match 'new', :to => 'takes#new'
    match 'new' => 'takes#create', :via => :post
  end

  resources :takes

  scope '/answers' do
    match '/', :to => 'homeworks#index', :via => :get
    match '/' => 'answers#create', :via => :post
    match '/new/:homework_id' => 'answers#new', :via => :get
    match '/download/:answer_id', :to => 'answers#download'

    match '/grade/:answer_id', :to => 'answers#grade', :via => :get
    match '/grade/:answer_id', :to => 'answers#grade_update', :via => :post
  end

  resources :answers, :except => [:index]

  match '/help', :to => 'helps#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_filter :require_teacher, :except => []
  before_filter :require_admin, :only => [:destroy]

  # GET /courses
  def index
    @title = "Course List"

    @courses = Course.all
  end

  # GET /courses/new
  def new
    @title = "Course Creating"

    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @title = "Course Editing"

    @course = Course.find(params[:id])
  end

  def show
    @courses = Course.all
    render :action => "index"
  end

  # POST /courses
  # POST /courses.json
  def create
    @course            = Course.new(params[:course])
    @course.updated_by = current_user.username

    if @course.save
      redirect_to '/courses', :notice => 'Course was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course            = Course.find(params[:id])
    @course.updated_by = current_user.username

    if @course.update_attributes(params[:course])
      redirect_to '/courses', notice: 'Course was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_url
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <%= render :partial => "shared/user_error", :locals => { :model_object => @course } %>

  <div id="field">
    <%= f.label :course_code %>
    <%= f.text_field :course_code, :required => "required" %>

    <%= f.label :thai_course_name %>
    <%= f.text_field :thai_course_name %>

    <%= f.label :english_course_name %>
    <%= f.text_field :english_course_name %>

    <%= f.submit "Submit", :disable_with => "Submitting...", :class => "action-btn green" %>
  </div>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Course's List</h1>

<div class="config">
  <%= link_to 'New Course', new_course_path %>
</div>

<% if @courses.empty? %>
  <div id="notice" class="text-center">Not found any course in the list</div>
<% else %>
  <table id="table">
    <tr>
      <th>Course Code</th>
      <th>Course Name</th>
      <th></th>
      <th></th>
    </tr>

    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_code %></td>
        <td><%= "#{course.thai_course_name} (#{course.english_course_name})" %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td>
          <% if admin? %>
            <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
<% end %>
</table>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>